<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGuvuefv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGuvuefv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGuvuefv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGuvuefv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGuvuefv\App_KernelDevDebugContainer([
    'container.build_hash' => 'Guvuefv',
    'container.build_id' => '9160b85d',
    'container.build_time' => 1723660992,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGuvuefv');
