<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_user' => [[], ['_controller' => 'App\\Controller\\ApiController::getAuthenticatedUser'], [], [['text', '/api/user']], [], [], []],
    'app_authentification' => [[], ['_controller' => 'App\\Controller\\AuthentificationController::index'], [], [['text', '/authentification']], [], [], []],
    'add_product' => [[], ['_controller' => 'App\\Controller\\ProductController::addProduct'], [], [['text', '/api/products']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], [], []],
    'signup' => [[], ['_controller' => 'App\\Controller\\SignupController::signup'], [], [['text', '/signup']], [], [], []],
    'addproduct' => [[], ['_controller' => 'App\\Controller\\ProductController::addProduct'], [], [['text', '/api/products']], [], [], []],
];
