<?php

namespace Container5PvsC0L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VRN9hkfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VRN9hkf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VRN9hkf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ApiController::getAuthenticatedUser' => ['privates', '.service_locator.st3ASTR', 'get_ServiceLocator_St3ASTRService', true],
            'App\\Controller\\ProductController::addProduct' => ['privates', '.service_locator.wWH4uhe', 'get_ServiceLocator_WWH4uheService', true],
            'App\\Controller\\ProductController::listProducts' => ['privates', '.service_locator.8chbYI7', 'get_ServiceLocator_8chbYI7Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ApiController:getAuthenticatedUser' => ['privates', '.service_locator.st3ASTR', 'get_ServiceLocator_St3ASTRService', true],
            'App\\Controller\\ProductController:addProduct' => ['privates', '.service_locator.wWH4uhe', 'get_ServiceLocator_WWH4uheService', true],
            'App\\Controller\\ProductController:listProducts' => ['privates', '.service_locator.8chbYI7', 'get_ServiceLocator_8chbYI7Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ApiController::getAuthenticatedUser' => '?',
            'App\\Controller\\ProductController::addProduct' => '?',
            'App\\Controller\\ProductController::listProducts' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ApiController:getAuthenticatedUser' => '?',
            'App\\Controller\\ProductController:addProduct' => '?',
            'App\\Controller\\ProductController:listProducts' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
