# config/services.yaml
services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: [ 'controller.service_arguments' ]

    App\Controller\SignupController:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $passwordHasher: '@security.password_hasher'
        public: true

parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'
